### ISSUE TITLE
Location should be pulled from resource group

### ISSUE THREAD

**Issue by SorraTheOrc** [CatalystAUInf/azure-moodle-autoscale#1]
There is a parameter for location, unless there is a good reason for this being distinct from the resource group location we should automatically pull the value from the resource group. This can be achieved with:

```
"location": "[resourceGroup().location]"
```

**Comment by SorraTheOrc** [comment]
One reason why this might not be how things are implemented right now is that a resource group can be created in any region whereas some resources are only available in specific regions. I note that the list of available regions in this template is quite narrow.

**Comment by CatalystAUInf** [comment]
The location parameter existed but as far as I can tell was never used. The nested templates pulled from the resource group. This parameter has been removed.
