### ISSUE TITLE
Standard_D1 not aviailable in all regions but hard coded in elasticTemplate

### ISSUE THREAD

**Issue by SorraTheOrc** [CatalystAUInf/azure-moodle-autoscale#4]
By defaults params file is set to Standard_D1, but this is not available in all regions (e.g. WestUS, which is also a default).

We should strive to only allow combinations that will work in all regions.

See also #1

**Comment by SorraTheOrc** [comment]
Actually, it turns out to be more of an issue than I thought. None of my parameters are set to Standard_D1.

The error occurs in the elasticTemplate. The parameter in question is "vmSize" which is set to Standard_D1 in the [template itself](https://github.com/CatalystAUInf/azure-moodle-autoscale/blob/master/nested/elastic.json#L45)

**Comment by SorraTheOrc** [comment]
In the params file there is an "elasticVmSku" which I have set to "Standard_DS2_v2". My expectation is that this would be carried through to the elasticTemplate. Either my expectation is incorrect (in which case is the parameter poorly named?) or there is a bug.

**Comment by CatalystAUInf** [comment]
This was actually a forgotten implementation on the elastic.json template. It has now been fixed.
